"""phase4_parent_safety_flag_and_alerts

Revision ID: 9f194421a0c6
Revises: d8909e3e5f75
Create Date: 2026-07-20 00:47:58.480357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f194421a0c6'
down_revision: Union[str, Sequence[str], None] = 'd8909e3e5f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snippet', sa.String(), nullable=True),
    sa.Column('kc_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_child_id'), 'alerts', ['child_id'], unique=False)
    op.add_column('interaction_events', sa.Column('safety_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interaction_events', 'safety_flag')
    op.drop_index(op.f('ix_alerts_child_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
