"""initial schema

Revision ID: 9f229414e92b
Revises: 
Create Date: 2026-07-15 00:09:38.652651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f229414e92b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('reading_level', sa.String(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('neurodivergence', sa.JSON(), nullable=False),
    sa.Column('current_topic', sa.String(), nullable=True),
    sa.Column('current_books', sa.JSON(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_profiles_device_id'), 'child_profiles', ['device_id'], unique=True)
    op.create_table('mastery_state',
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('kc_id', sa.String(), nullable=False),
    sa.Column('p_mastery', sa.Float(), nullable=False),
    sa.Column('p_learn', sa.Float(), nullable=False),
    sa.Column('p_slip', sa.Float(), nullable=False),
    sa.Column('p_guess', sa.Float(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty_d', sa.Float(), nullable=True),
    sa.Column('card_state', sa.String(), nullable=True),
    sa.Column('next_review', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('child_id', 'kc_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_child_id'), 'sessions', ['child_id'], unique=False)
    op.create_table('interaction_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('kc_id', sa.String(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('hint_used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_events_child_id'), 'interaction_events', ['child_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_events_child_id'), table_name='interaction_events')
    op.drop_table('interaction_events')
    op.drop_index(op.f('ix_sessions_child_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('mastery_state')
    op.drop_index(op.f('ix_child_profiles_device_id'), table_name='child_profiles')
    op.drop_table('child_profiles')
    # ### end Alembic commands ###
