"""add child_fsrs_params

Revision ID: d8909e3e5f75
Revises: 9f229414e92b
Create Date: 2026-07-16 10:10:56.088474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8909e3e5f75'
down_revision: Union[str, Sequence[str], None] = '9f229414e92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_fsrs_params',
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child_profiles.id'], ),
    sa.PrimaryKeyConstraint('child_id')
    )
    op.drop_index(op.f('ix_child_profiles_device_id'), table_name='child_profiles')
    op.create_index(op.f('ix_child_profiles_device_id'), 'child_profiles', ['device_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_child_profiles_device_id'), table_name='child_profiles')
    op.create_index(op.f('ix_child_profiles_device_id'), 'child_profiles', ['device_id'], unique=False)
    op.drop_table('child_fsrs_params')
    # ### end Alembic commands ###
